### ISSUE TITLE
How to just update? [Update from 5.1.x to 6.0.x]

### ISSUE THREAD

**Issue by xiaotan828** [theme-next/hexo-theme-next#1]
First issue... I'm sorry I don't have much knowledge
I've made a lot of personal changes in my previous files which should be 5.1.3 version, how can I simply update the theme, so I can keep the previous change. 
Thx!

**Comment by ivan-nginx** [comment]
@xiaotan828 there are not hard breaking changes between 5.1.3 / 5.1.4 and 6.0.0. It's just 6x because rebase repo and some `libs` moved out to external repos. See [here](https://github.com/theme-next) wich was moved out from `next/source/lib` directory.

Secondly, `hexo-wordcont`plugin was replaced by `[hexo-symbols-count-time](https://github.com/theme-next/hexo-symbols-count-time)` and all `wordcount`settings was replaced by `hexo-symbols-count-time` settings, that's all.

I try today to make release and give detailed instructions how to smooth update from 5.1.x to 6x without troubles. Need just some time.

**Comment by ivan-nginx** [comment]
Hi! Thre is some isntructions for update from 5 to 6: https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md

**Comment by ivan-nginx** [comment]
@xiaotan828 hey, just pasted: https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md

**Comment by ivan-nginx** [comment]
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x
