### ISSUE TITLE
custom favicon not working

### ISSUE THREAD

**Issue by swpd** [theme-next/hexo-theme-next#2]
Putting custom favicon.ico into `hexo-site/source` didn't work after updating to NexT v6.0.0.

**Comment by ivan-nginx** [comment]
You put your favicon into `hexo-site/source/` or `hexo-site/source/images`?

There is documentation in config file:

To get or check favicons visit: https://realfavicongenerator.net
Put your favicons into `hexo-site/source/` (recommend) or `hexo-site/themes/next/source/images/` directory.

Default NexT favicons placed in `hexo-site/themes/next/source/images/` directory.
And if you want to place your icons in `hexo-site/source/` root directory, you must remove `/images` prefix from pathes.

For example, you put your favicons into **`hexo-site/source/images`** directory.
Then need to rename & redefine they on any other names, otherwise icons from Next will rewrite your custom icons in Hexo.

**Comment by swpd** [comment]
I put my `favicon.ico` under the `hexo-site/source/` root directory, should I update the favicon path in `_config.yml` as well?
Such as:
```
favicon:
     small : /favicon.ico
```
An earlier release version of NexT doesn't require such an update though.

**Comment by ivan-nginx** [comment]
> An earlier release version of NexT

What earlier version? This version have no breaking changes in favicon between 5.1.3 / 5.1.4. New favicon style was added in 5.1.3 version, see here [releases notes](https://github.com/iissnan/hexo-theme-next/releases/tag/v5.1.3).

> should I update the favicon path

Of cource u should. Try to:

**1.** Put your favicons into `hexo-site/source/images` directory. For example, your icon named `swpd.ico`, so, path will be `hexo-site/source/images/swpd.ico`.
**2.** Then in NexT config section:
```yml
favicon:
  small: /images/swpd.ico
```
**3.** After that to check icon use https://realfavicongenerator.net (your browser may cache previous NexT icon, so, need to clear cache).

**Comment by swpd** [comment]
> What earlier version?

v5.1.2. The only config of favicon was `favicon: /favicon.ico` in this version.

So after new favicon style was added, I only need to config `favicon>small` if I don't care about responsive favicon, right?

**Comment by ivan-nginx** [comment]
> I only need to config favicon>small if I don't care about responsive favicon, right?

U can set only 1 icon, right.

U can also see [here](https://github.com/iissnan/hexo-theme-next/issues/1920) about favicon.

**Comment by swpd** [comment]
OK. Thank you.
