### ISSUE TITLE
a little bug in cdn

### ISSUE THREAD

**Issue by bitwater1997** [theme-next/hexo-theme-next#260]
https://github.com/theme-next/hexo-theme-next/blob/d2c74b3b102586b705619006387d59d95156b5c4/layout/_partials/head/head.swig#L32

https://github.com/theme-next/hexo-theme-next/blob/d2c74b3b102586b705619006387d59d95156b5c4/_config.yml#L932

variable not equal

**Comment by sli1989** [comment]
There has corresponding code.

https://github.com/theme-next/hexo-theme-next/blob/1f9ef9c2a9ea187ad2b22e5cfbcbe3842e0f25b4/layout/_partials/head/head.swig#L30-L36

But Don't know the meaning of `han`.

**Comment by ivan-nginx** [comment]
Oh! Nice catch, @bitwater1997 :+1: 
Please, guys, fix this somebody.

**Comment by sli1989** [comment]
Fixed in 4cacb103b1350b8e3805f343d2c86932a9de383d.

- false

![0-2](https://user-images.githubusercontent.com/8521181/39507499-bdf1a68e-4e10-11e8-97e3-e67386bd43f0.png)

- true + local lib

![1](https://user-images.githubusercontent.com/8521181/39507526-dcb350d6-4e10-11e8-93c3-fbe1a74c0dee.png)

- true + theme.vendors.han

![1-2](https://user-images.githubusercontent.com/8521181/39507543-f48d167e-4e10-11e8-9930-4abb585538ed.png)

- true + theme.vendors.Han

![1-3](https://user-images.githubusercontent.com/8521181/39507556-01b2e13a-4e11-11e8-8082-96a5fabec146.png)
