### ISSUE TITLE
fullimage标签插入的图片没有居中显示

### ISSUE THREAD

**Issue by bailangsyc** [theme-next/hexo-theme-next#284]
主题的版本是：version: 5.1.3， 使用的是：Pisces。使用fullimage标签插入图片时，插入的图片没有居中显示。效果图如下：
![](http://media.shaoyance.com/2018-05-07%2023-17-18%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by ivan-nginx** [comment]
Fixed in 5a70fd32c5565771e93de5c364b4596c5a197e07
Released in [NexT v6.0.2](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.2)

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

**Comment by bailangsyc** [comment]
ok, thank you very much, I will try it tomorrow!

**Comment by ivan-nginx** [comment]
Don't forget close it, if will solved.
