### ISSUE TITLE
<link rel="canonical" href="URL"/> is wrong!

### ISSUE THREAD

**Issue by khs1994** [theme-next/hexo-theme-next#40]
You can see website source!

我看了一下 6.0.1 主题，生成的网页 

`<link rel="canonical" href="URL"/>` 没有和当前页面对照起来。

`view-source:https://leaferx.online/2017/01/30/Bottomheart/`

查找 `canonical` 关键字

**Comment by ivan-nginx** [comment]
[Your site](https://www.khs1994.com):

`view-source:https://www.khs1994.com/linux/openssl/https/README.html`
`<link rel="canonical" href="https://www.khs1994.com/linux/openssl/https/README.html"/>`

What u want?

**Comment by ivan-nginx** [comment]
`canonical` wan not mofified since version 5 but issue is relevant to version 6 surprisingly.

Bug was detected on:
* https://leaferx.online » href="https://leaferx.online/categories/" (@LEAFERx)
* https://wafer.li » href="https://wafer.li/404.html" (@wafer-li)
* https://raincal.top » href="https://raincal.top/about/" (@Raincal)
* https://tsanie.us » href="https://tsanie.us/categories/" (@tsanie)

For now i don't understand why this bug exists. Need to check it deeper...

**Comment by khs1994** [comment]
I use `6.0.1` show this wrong,So I back to `5.x`!

**Comment by ivan-nginx** [comment]
@khs1994 yeah. thank's for report issue. Try to disable `cache` option and generate again. I think need just exclude `canonical` option from `cache` during generation.

**Comment by khs1994** [comment]
```bash
cache:
  enable: false
```

solved

**Comment by ivan-nginx** [comment]
Non totally solved, it's just temporarily around. Fix will ASAP.

**Comment by khs1994** [comment]
Thanks.

**Comment by ivan-nginx** [comment]
Fixed in bad433475a3cdcc420807ac8008a5018558e0622

**Comment by geekrainy** [comment]
Good job.

**Comment by wafer-li** [comment]
Thanks for notifying me that
