### ISSUE TITLE
Some Suggestions for the current version of the next theme are to be adopted. [libs cannot be back built-in NexT ]

### ISSUE THREAD

**Issue by iiskei** [theme-next/hexo-theme-next#46]
Program should do it out of the box, it is suggested that the next lib into source, avoid users touch not clear mind for the first time, but also caused some trouble to the person that often use, can download the lib

**Comment by ivan-nginx** [comment]
Don't understand your suggestion. What exactly u want? In short words.

**Comment by wafer-li** [comment]
@iiskei  
If your English is not so good, please use some screenshots and pictures to express your view.

Don't make the mistake I've ever made.

**Comment by iiskei** [comment]
I mean to put lib in the original next V5.1.4 into next 6.0. Is that clear?

**Comment by ivan-nginx** [comment]
:smile:  Yeah, it's clear but i change version mostly because this libs become separated and don't see any troubles to install needed. If u have bugs with this, issues are welcome.

Why it was maded? There are several reasons. And because NexT is growing up with each year, there are more and more external libs and:
1. General maintenance became a harder for all who not only use it, but help with development too.
2. Generation speed became slower and slower with each new library. Half of unused libs copied to public dirs for all users and search engines see all this libs too. It's mostly waste files for half NexT users.
3. Full amount of NexT distributive at least decrease about 2x, which provides faster download & update speed.

So, was **increased** **development speed**, **generation speed** and **download speed**.

If this is uncomfortable for u, u can use old 5.1.x version, but without at least my maintenance.
